import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

export const colors = {
  primary: "#6C63FF",
  secondary: "#FF6584",
  accent: "#43D97B",
  background: "#F9F9F9",
  text: "#333333",
  textLight: "#666666",
  white: "#FFFFFF",
  black: "#000000",
  error: "#FF5252",
  shadow: "rgba(0, 0, 0, 0.1)",
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    padding: width * 0.05,
  },
  header: {
    marginTop: height * 0.05,
    marginBottom: height * 0.03,
    alignItems: "center",
  },
  title: {
    fontSize: width * 0.07,
    fontWeight: "bold",
    color: colors.primary,
    textAlign: "center",
    marginBottom: height * 0.01,
  },
  subtitle: {
    fontSize: width * 0.04,
    color: colors.textLight,
    textAlign: "center",
    marginBottom: height * 0.02,
  },
  buttonContainer: {
    width: "100%",
    marginBottom: height * 0.03,
  },
  button: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: colors.white,
    borderRadius: width * 0.03,
    paddingVertical: height * 0.02,
    paddingHorizontal: width * 0.05,
    marginBottom: height * 0.02,
    elevation: 4,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
    height: height * 0.075,
  },
  buttonCamera: {
    backgroundColor: colors.primary,
  },
  buttonGallery: {
    backgroundColor: colors.secondary,
  },
  buttonSave: {
    backgroundColor: colors.accent,
  },
  buttonText: {
    color: colors.white,
    fontSize: width * 0.045,
    fontWeight: "bold",
    textAlign: "center",
  },
  imageContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: height * 0.02,
    marginBottom: height * 0.05,
  },
  image: {
    width: width * 0.85,
    height: width * 0.85,
    borderRadius: width * 0.04,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.1)",
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  noImageContainer: {
    width: width * 0.85,
    height: width * 0.85,
    borderRadius: width * 0.04,
    backgroundColor: colors.white,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.1)",
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  noImageText: {
    fontSize: width * 0.045,
    color: colors.textLight,
    textAlign: "center",
    padding: width * 0.05,
  },
  iconContainer: {
    width: width * 0.1,
    height: width * 0.1,
    borderRadius: width * 0.05,
    backgroundColor: "rgba(255,255,255,0.2)",
    justifyContent: "center",
    alignItems: "center",
    marginRight: width * 0.04,
    marginLeft: width * 0.01,
  },
  successMessage: {
    position: "absolute",
    bottom: height * 0.05,
    left: width * 0.1,
    right: width * 0.1,
    backgroundColor: colors.accent,
    padding: height * 0.02,
    borderRadius: width * 0.02,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  successText: {
    color: colors.white,
    fontSize: width * 0.04,
    fontWeight: "bold",
    marginLeft: width * 0.02,
  },
});
